Traceback (most recent call last):
  File "emails.py", line 29, in <module>
    main()
  File "emails.py", line 26, in main
    print(find_email(sys.argv))
  File "emails.py", line 19, in find_email
    fullname = str(argv[1] + " " + argv[2])
IndexError: list index out of range
