.E
======================================================================
ERROR: test_one_name (__main__.EmailsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./emails_test.py", line 15, in test_one_name
    self.assertEqual(find_email(testcase), expected)
  File "/home/<studentID>/scripts/emails.py", line 19, in find_email
    fullname = str(argv[1] + " " + argv[2])
IndexError: list index out of range

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=1)
